version: '3'
services:
  server:
    depends_on:
      - database
    build: ./
    networks:
      - mern-app
    # volumes:
    #  - ./api:/app
    #  - ./utils:/app/utils
    #  - ./package-lock.josn:/app/package-lock.json
    #  - ./package.json:/app/package.json
    #  - ./.env:/app/.env
    #  - /app/node_modules
    ports:
      - 8080:8080
    env_file:
     - ./.env
  client:
    depends_on:
      - server
    build: ./client
    networks:
      - mern-app
    # volumes:
    #  - ./client:/app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    env_file:
     - ./client/.env
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
     - data:/data/db

volumes:
  data:
networks:
  mern-app:
    driver: bridge
