version: '3'
services:
  server:
    depends_on:
      - database
    build: ./
    ports:
      - 8080:8080
    env_file:
     - ./.env
  client:
    depends_on:
      - server
    stdin_open: true
    build: ./client
    ports:
      - 5173:5173
    env_file:
     - ./client/.env
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
     - data:/data/db

volumes:
  data:
