
services:
  server:
    build: ./
    ports:
      - 8080:8080
    env_file:
      ./.env
    depends_on:
      - database
    develop:
      watch :
        - action: sync
          path: ./api
          target: ./app/api
        - action: sync
          path: ./utils
          target: ./app/utils
        - action: rebuild
          path: package.json
  client:
    build: ./client
    ports:
      - 5173:5173
    env_file:
      ./client/.env
    depends_on:
      - server
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: ./app/src
        - action: rebuild
          path: ./client/package.json
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
